### ISSUE TITLE
support .vue

### ISSUE THREAD

**Issue by fyyyyy** [surdu/selector-to-tag#25]
In .vue files, markup is mixed with javascript which lives inside <script> tags.
It would be great if this was auto-disabled within <script> tags

**Comment by surdu** [comment]
You can add the .vue extension to the "File extensions" in the settings

**Comment by fyyyyy** [comment]
Yes, that works. But then its also active within the JS code and this will prevent any js autocomplets

**Comment by surdu** [comment]
That's one downside, yes :(. Using vue's single file components will bring you more of this problems in the future. Personally, I would have loved vue more if they would have omitted this "feature".

But coming back to the subject: I see this to much as a corner case in order to embed this functionality into this package. React has it's own similar thing, which would bring another corner case and the list could get out of control eventually.

Sorry 😞
