### ISSUE TITLE
Possible way of adding new selectors!

### ISSUE THREAD

**Issue by AndrewBestbier** [surdu/selector-to-tag#5]
Hey! Thanks for developing this awesome tool. I just had a thought of an efficient way of adding custom selectors. 

The syntax could be like this:
div#exampleId.exampleClass1.exampleClass2{layout:column}

Which would translate to this:
div id="exampleId" class="exampleClass1 exampleClass2" layout="column"

(I couldn't write the full html in this comment for some reason)

What do you think?

**Comment by surdu** [comment]
Hello, the whole idea of this extension was to write more with less. 

In case of attributes, for me at least, it makes less sense to bother writing `{layout:column}` in order to result in `layout="column"`, effectively typing the same amount.

I though myself of the same thing, but using the 'more CSS like' approach `[layout=column]`, but realized it doesn't quite help.

Thank you very much for the feedback, but at least for now, I don't see this as a feature for the package.

**Comment by AndrewBestbier** [comment]
Fair enough :) Thanks for the response
